version: '2'

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    enabled: true
    config:
      threshold: # Language-specific defaults. Overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: # Language-specific defaults. Overrides affect all languages.

exclude_patterns:
  - '.github/'
  - 'cypress/'
  - 'docs/'
  - '.env.template'
  - '.eslintrc.cjs'
  - '.gitignore'
  - 'cypress.config.ts'
  - 'vite.config.ts'
  - '**/*.css'
  - '**/*.html'
  - '**/*.json'
  - '**/*.md'
  - '**/*.yml'
