name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Create .env file
        run: echo "VITE_TOKEN=${{ secrets.VITE_TOKEN }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run lint

      - name: Format with Prettier
        run: npm run format

      - name: Run tests with Cypress on Chrome
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: chrome

      - name: Run tests with Cypress on Firefox
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: firefox

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*

      - name: Generate code coverage report
        run: npm run coverage

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

      - name: Upload code coverage report to Code Climate
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
